### ISSUE TITLE
README needs an update

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-web-account#13]
Read Me should at least list the methods in the module and a short a description.
Maybe a link to the contributor guidelines too (which I need to read more).

**Comment by mattcollier** [comment]
@aljones15 I recently used this module to generate a readme automatically from jsdocs code: https://github.com/jsdoc2md/jsdoc-to-markdown#readme

Here's the repo to show example generation.
https://github.com/digitalbazaar/base64url-universal

We're in no way married to this jsdoc-to-markdown module.  But you could start by running it on this code and see if you get something useful?  If this can be done nicely using some other tooling, bring it!

Also, if you decide to work on this.  Keep in mind that the end goal would be to have it in an npm script that we could run as part of a release process to keep the readme up-to-date.  If the readme flows directly from jsdocs, I think devs will be more inclined to write good jsdocs.  I know I would.

**Comment by aljones15** [comment]
this is genius and a good idea so I will work on this for bedrock-web-account in a second and then maybe add it to the https://github.com/digitalbazaar/bedrock-vue-address-form
which is also lackinng a little docs.

**Comment by aljones15** [comment]
@mattcollier 

First draft:

https://github.com/digitalbazaar/bedrock-web-account/blob/enhancement/jsdoc-to-markdown-readme/test.md

the script is readme.js

looks we just need a template like handbrake uses:
https://github.com/75lb/handbrake-js/tree/master/jsdoc2md

**Comment by mattcollier** [comment]
@aljones15 nicely done, please create a PR for this branch for the sake of discussion.

Does the jsdoc-markdown module already have the goods when it comes to injecting the generated stuff into a readme if the right templating is in place?

@davidlehn has ideas about this project as well.

**Comment by aljones15** [comment]
@mattcollier @davidlehn  let me correct some typos first
the other thing I wanted to do was make a readme template.
right now I simply append the text from up top to the stuff on the bottom.

Take a look at this: 

https://github.com/75lb/handbrake-js/tree/master/jsdoc2md

it is used as the template for their readme:

https://github.com/75lb/handbrake-js

I think would be better if we could figure out the template rules so if a project
needs to have a more complex layout than just header whatever it could.

**Comment by davidlehn** [comment]
Yeah, I was playing with that tool a while ago on jsonld.js.  Looks easier to use a template and the command line tool vs a script for generation.  That's what I was playing with at least.  I'm also unsure if it's better to put the API in the README or link to a API.md.  An API doc template would be smaller and easier to edit and maybe more portable between projects?  But maybe also would duplicate things?  I'm not sure.  If the API is large, I think a second doc makes more sense.  FWIW, in jsonld.js I had been pondering some quick startup docs in README and link those APIs off into the full docs in a generated `docs/api.md` file.  Some experimentation is needed with all this.

**Comment by aljones15** [comment]
@davidlehn if the handbrake example is anything to go you basically just add this the bottom of your existing read me

```md
# API Reference
{{#module name="handbrake-js"}}
{{>body~}}
{{>member-index~}}
{{>separator~}}
{{>members~}}
{{/module}}
```

and that's it. 
so no real need for a universal template just take the existing READMEs and append some lines to it. how did you get your template working? I have not really gotten into it yet.

the command they use is

```
    "docs": "jsdoc2md -t jsdoc2md/README.hbs lib/*.js index.js > README.md; echo"
```

ahh ok the template is made in [handlebars.js](https://handlebarsjs.com/)

**Comment by davidlehn** [comment]
Yeah, I understand the mechanics of it.  I'm questioning if that's the best way to do it for anything but code with a very short API.  Probably depends on the code.  Probably nicer to have a static README that's easily editable without a generation step if you didn't touch the API comments.  There's other info in there like intro, contact, links, etc.  Hard to use, say, github site editor with preview for drive-by contributions if there's a generation step involved.

**Comment by aljones15** [comment]
if the api does get to big then linking to other mark down files seems like a good solution. With bedrock-web-account I would be surprised it every gets to large ,but we could generate a markdown doc for either module then in the read me link to them
so one generated file for RegisterContoller one for AccountServe with a link to each in the original read me.
